### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by ProXAlex** [X-rus/xNet#1]
Подскажи пожалуйста, как с помощью библиотеки отправлять post ну и get запросы на httpS.
Как подключить сертификаты. Если можно с примером. И ещё 1 вопрос. Куки сохраняются после ответа, и при следующем запросе используются уже они?
Извиняюсь за вопросы и время. Заранее спасибо.

**Comment by mazanuj** [comment]
При подключении через прокси работать отказывается
