### ISSUE TITLE
ТАКАЯ хорошая библиотека пропадает! 

### ISSUE THREAD

**Issue by Radzhab** [X-rus/xNet#18]
Ну что вы так все забросили((((((((((((

**Comment by Radzhab** [comment]
Будут обновы)?

**Comment by X-rus** [comment]
Только правки багов. Вчера залил новую версию.

**Comment by mat0thew** [comment]
@Radzhab для чего ее используете?

**Comment by Radzhab** [comment]
Для автоматизациия парсинга и пр
