### ISSUE TITLE
Повтор Address.Host в Url запроса

### ISSUE THREAD

**Issue by MrQwert** [X-rus/xNet#20]
Вот часть файла /Net/~Http/HttpRequest.cs, отвечающая за генерацию первой строки запроса (```GenerateStartingLine```)
```
            if (_currentProxy != null &&
                (_currentProxy.Type == ProxyType.Http || _currentProxy.Type == ProxyType.Chain))
            {
                query = Address.AbsoluteUri;
            }
            else
            {
                query = Address.PathAndQuery;
            }
```
Если прокси используется и его тип - Http или Chain, использовать AbsoluteUri (```GET https://site.com/file?parameter=value HTTP/1.1```) 
Иначе - использовать PathAndQuery (```GET /file?parameter=value HTTP/1.1```).

При использовании прокси (в данном случае локального Charles) запрос отправляется на ```https://site.comhttps://site.com/file?parameter=value``` вместо ```https://site.com/file?parameter=value```

**Comment by MrQwert** [comment]
Обновил стартпост.

**Comment by VitalikShalamay** [comment]
как решили то?
