### ISSUE TITLE
xNet Recconect

### ISSUE THREAD

**Issue by ParadoxFilm** [X-rus/xNet#22]
Приветствую, Руслан! Во-первых, конечно, надеюсь что до вас дойдёт это сообщение в ближайшее время, где я бы очень хотел передать огромную благодарность за создание такой прекрасной библиотеки, как xNet. А в особенности радует то, что проект до сих пор обновляется на гитхабе, и последнее обновление было ~ две недели назад.
Так собственно вот в чём дело: я бы хотел предложить одну интересную штуку, жизненно нужную, в том числе для меня. Это рекконект со всеми его вытекающими. Это очень важно при работе через прокси, т.к. они имеют свойство отваливаться, но через некоторое кол-во миллисекунд снова возвращаться в строй. Для решение этой проблемы мне пришлось вставить свои костыли в виде кривой реализации рекконекта (т.е. всё работает, но нарушена структура вашего кода) в вашу библиотеку, но у вас вышла новая версия и я подумал, что вы можете заинтересоваться этим и реализовать всё как полагается...
 Конкретно:
- Добавить в "HttpRequest" bool параметр, с названием вроде "HttpRequest.Recconect", отвечающий за то, пытаться ли подключиться/принять данные, если уже была неудачная попытка оного (по умолчанию предлагаю поставить false).
- Добавить в "HttpRequest" int(byte?) параметр, с названием вроде "HttpRequest.RecconectLimit", отвечающий за то, сколько максимально попыток рекконекта можно предпринять (по умолчанию предлагаю поставить три попытки).
- Добавить в "HttpRequest" int параметр, с названием вроде "HttpRequest.RecconectDelay", отвечающий за то, какую сделать задержку между попытками подключиться/принять данные (по умолчанию предлагаю поставить 100 мс).
В итоге, выходит, например так:

HttpRequest Request = new HttpRequest();

Request.Recconect = true; //пытаться переподключится...

Request.RecconectLimit = 3; //максимальное кол-во попыток рекконекта

Request.RecconectDelay = 150; //задержка между попытками рекконекта

-------------------------------
Чтобы было совсем идеально, круто бы было в Responce добавить в выводе int(byte?) параметр (с названием, например, RecconectCount), который бы показывал, сколько попыток рекконекта было осуществлено. Что-то вроде:

HttpResponse Responce= Request.Get("http://ya.ru");

MessageBox.Show("Кол-во рекконектов: "+Responce.RecconectCount); //выведет количество попыток рекконекта...

P.S. Тогда ваша библиотека будет ещё ближе к идеальной :)
Очень надеюсь, что не останусь без ответа... Удачи вам!

**Comment by X-rus** [comment]
Приветствую. Да, можно добавить эту штуку. Прямо в таком виде.

Сейчас в библиотеки есть реконнект связанный с keepalive, но я его тогда удалю. Добавлю для этих случаев keepalive timeout (30 сек по умолчанию), и теперь постоянные соединения будут отключены по умолчанию.

**Comment by ParadoxFilm** [comment]
Большое спасибо за ответ! Буду ждать :)

**Comment by X-rus** [comment]
Добавил reconnect - https://github.com/X-rus/xNet/releases
Пожалуй, это последнее подобное обновление. Теперь буду только вносить фиксы багов.

**Comment by ParadoxFilm** [comment]
Спасибо, буду пробовать :)
Ну, вы вроде всё реализовали что надо для работы с http, так что только баги и остаётся фиксить (ежели будут выявлены)...
