### ISSUE TITLE
Значение заголовка 'Authorization' можно задать только с помощью специального свойства.

### ISSUE THREAD

**Issue by Radzhab** [X-rus/xNet#28]
Дайте нам самим пихать данные в Autorization

**Comment by X-rus** [comment]
Какую версию xNet используешь?

**Comment by Radzhab** [comment]
хз) которая на компе была. Скорее всего устарела как я понимаю8?)

**Comment by Radzhab** [comment]
+ 1 хотелка. Добавить в nuget.
