### ISSUE TITLE
Ответ сервера при HTTP ошибке. 

### ISSUE THREAD

**Issue by Fedorus** [X-rus/xNet#42]
Ситуация: сервер в ответ на Post-запрос выдаёт ошибку 400, в результате вылетает HttpException. Но! Сервер кроме кода ошибки выдаёт ещё и содержательный ответ, что не так в запросе. Как его получить?

**Comment by avQse** [comment]
Свойство IgnoreProtocolErrors у HttpRequest, установить в true
